[package]
name = "open-url-in"
version = "0.1.0"
edition = "2024"

[dependencies]
gtk = { version = "0.10.3", package = "gtk4", features = ["v4_18"] }

[profile.release]
panic = 'abort'

[profile.dev]
panic = 'abort'
